theme: jekyll-theme-minimal
logo: /assets/img/521D2AD1-978F-45A6-A9D0-580A63B52990.png
title: <a href="./">CHANGE LOG</a>
google_analytics: G-SFJ80L12D6
imageone: <img src="https://cdn.discordapp.com/attachments/806343355264401478/837569890357346334/image0.png" alt="Blog"/>
lineone: <a href="http://fw.hcr2.info">Friendly Wars</a> - <a href="http://tw.hcr2.info">Tractor Wars</a> - <a href="http://vehicles.hcr2.info">Vehicles</a>
linetwo: <a href="http://blog.hcr2.info">Log</a> - <a href="http://tips.hcr2.info">Tips</a> - <a href="http://chests.hcr2.info">Chests</a> - <a href="http://memes.hcr2.info">Memes</a> - <a href="http://gm.hcr2.info">GM</a> - <a href="http://faq.hcr2.info">FAQ</a>
buttonone: <a href="http://hcr2.info">Reference <strong>hcr2.info</strong></a>
buttontwo: <a href="#top">Page <strong>top</strong> </a>
buttonthree: <a href="#bottom">Page <strong>bottom</strong></a>
      
